version: 2
updates:
- package-ecosystem: gitsubmodule
  directory: "/."
  schedule:
    interval: daily
    time: "00:00"
    timezone: Australia/Adelaide
  open-pull-requests-limit: 99
  reviewers:
  - laitingsheng
  assignees:
  - laitingsheng
  labels:
  - dependabot
  - enhancement
