version: 2
updates:
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - laitingsheng
    assignees:
      - laitingsheng
    labels:
      - dependabot
      - enhancement
