version: 1
update_configs:
  - package_manager: submodules
    directory: ./
    update_schedule: daily
    default_assignees:
      - laitingsheng
    default_reviewers:
      - laitingsheng
    default_labels:
      - dependabot
      - enhancement
